# Create a draft release when a tag is pushed
name: Create a release

on:
  # Allow manual trigger from the Actions tab:
  # https://github.com/Automattic/chatrix-frontend/actions/workflows/release.yml
  workflow_dispatch:

  push:
    tags: ['v*']

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: yarn install && yarn build

      - name: Create directory for release
        run: cp -r target chatterbox

      - name: Create archive for release
        run: tar -cvzf chatterbox-${{ github.ref_name }}.tar.gz chatterbox

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          artifacts: "chatterbox-${{ github.ref_name }}.tar.gz"
          artifactErrorsFailBuild: true
          draft: true
