# Create a draft release when a tag is pushed
name: Create a release

on:
  # Allow manual trigger from the Actions tab:
  # https://github.com/Automattic/chatrix/actions/workflows/release.yml
  workflow_dispatch:

  push:
    tags: ['v*']

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build chatrix
        run: ./scripts/build.sh

      - name: Create directory for chatrix release
        run: cp -r target chatrix-frontend

      - name: Remove unnecessary files and directories
        run: |
            rm -rf chatrix-frontend/config.dev.json

      - name: Create archive for chatrix release
        run: tar -cvzf chatrix-frontend-${{ github.ref_name }}.tar.gz chatrix-frontend

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          artifacts: "chatrix-frontend-${{ github.ref_name }}.tar.gz"
          artifactErrorsFailBuild: true
          draft: true
